"""empty message

Revision ID: 15d51ae58424
Revises: 
Create Date: 2024-02-11 20:32:22.785991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d51ae58424'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_firstname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_surname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('user_surname')
        batch_op.drop_column('user_firstname')

    # ### end Alembic commands ###
