"""Added three columns to reviews table

Revision ID: 44eae04471d5
Revises: 85093c77ed34
Create Date: 2024-02-08 10:31:17.333063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44eae04471d5'
down_revision = '85093c77ed34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_firstname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_surname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('user_surname')
        batch_op.drop_column('user_firstname')

    # ### end Alembic commands ###
